### ISSUE TITLE
v0.1.2

### ISSUE THREAD

**Issue by rana** [rana/GCP.jl#4]
@JuliaRegistrator register()

**Comment by RoyiAvital** [comment]
Can I edit files in Google Drive using this? Like a Google Sheet Document?

**Comment by rana** [comment]
Not at the moment. Those particular APIs would need to be added.

**Comment by rana** [comment]
> Can I edit files in Google Drive using this? Like a Google Sheet Document?

Not at the moment. Those particular APIs would need to be added.

**Comment by RoyiAvital** [comment]
Do you have any plans to?
It would be really great.

**Comment by rana** [comment]
@RoyiAvital No plans. I've moved on. Feel free to write them :smiley:

**Comment by RoyiAvital** [comment]
Did you leave the Julia eco system? Or just left Google Cloud?

**Comment by rana** [comment]
I set both Julia and GCP aside for the time being. Both are good and fine. My needs and time have just shifted in different directions. Currently focusing on the Rust ecosystem. I may eventually implement more machine learning with Julia, after re-evaluating machine learning advancements. The GCP account is ready and waiting. :grinning: 

What are you goals and interests? Understanding those focuses me in a particular direction.

**Comment by RoyiAvital** [comment]
I just needed something to download a certain Google Sheet, process it as a table and update results back to the online file.

I see many people shift to Rust.
It seems to have a lot of inertia this days.
